#!/bin/sh

set -e

lb config noauto \
	--binary-image iso-hybrid \
	--backports true \
	--cache true \
	--image-name "debian-junior-live-image-0.1.0-alpha-4" \
	--distribution bookworm \
	--hdd-label "DEBIAN_JR_LIVE" \
	--bootappend-live \
	"boot=live components noroot persistence \
	hostname=debianjr username=user \
	locales=de_DE.UTF-8,en_US.UTF-8 keyboard-layouts=de,us timezone=Europe/Berlin  \
	" \
	"${@}"
