#!/bin/sh

set -e

lb config noauto \
    --binary-image iso-hybrid \
    --backports true \
    --cache true \
    --image-name "debian-live-${DISTRIBUTION}-${LIVE_VERSION}" \
    --distribution ${DISTRIBUTION} \
    --hdd-label "DEBIAN_LIVE" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --bootappend-live \
    "boot=live components persistence \
    hostname=debian username=user \
    locales=en_US.UTF-8 keyboard-layouts=us timezone=America/New_York  \
    " \
    "${@}"
